export { AddPost } from './AddPost/AddPost'
export { FullPost } from './FullPost'
// export { Profile } from './Profile'
export { Home } from './Home'
export { Login } from './Login/Login'
export { Registration } from './Registration/Registration'
